### ISSUE TITLE
Rich Presence U is invisible

### ISSUE THREAD

**Issue by DaolioKun** [ninstar/Rich-Presence-U#10]
every time I open rich presence U, it is invisible, I alredy tried instaling the 2 versions, and neither of them worked
![image](https://user-images.githubusercontent.com/90862033/133657094-7157ff40-3a87-4b39-a75d-2acf785d0bab.png)

**Comment by ninstar** [comment]
First close the app, type `%appdata%/RichPresenceU` in the address bar of your file explorer, then delete `preferences.cfg`.
