### ISSUE TITLE
Mac build?

### ISSUE THREAD

**Issue by highjeans** [ninstar/Rich-Presence-U#11]
Will there be a mac version of this? I really want to use this software.

**Comment by ninstar** [comment]
Unfortunately I have no plans to make a Mac version, as I never used that OS.

**Comment by highjeans** [comment]
The project does contain failed for building on macs so I mean you could do it anyways. There are many mac users who want something like this right now.

**Comment by ninstar** [comment]
Yes it does have files for compiling on Mac (as GMS generate those), but as I said I never used Mac nor I have a computer with a Mac OS installed, so I'm unable to build it on that platform.

**Comment by highjeans** [comment]
You know you can use a vm or have me help out as I am a mac user myself.

**Comment by highjeans** [comment]
Plus I was able to clone the repository and get the app running on my mac but nothing would work except for the fact that the ui showed up.

**Comment by ninstar** [comment]
I macOS build is now available, I close it for now.
