### ISSUE TITLE
Discord Account Not Connecting

### ISSUE THREAD

**Issue by Snare-Hawk** [ninstar/Rich-Presence-U#12]
Even after waiting several minutes, my Discord account never sees to connect to the application. I've tried uninstalling and reinstalling and have made sure I am signed in on browser and the Discord app, both to no avail.

![image](https://user-images.githubusercontent.com/85657152/155046328-6e972603-23e8-4e63-a750-ae2a9ef3ec2c.png)

**Comment by ninstar** [comment]
Have you tried one of the solutions in the troubleshooting section?

**Comment by Snare-Hawk** [comment]
> Have you tried one of the solutions in the troubleshooting section?

I had changed the drive to which I installed Windows because my previous one was dying and causing some other issues, so I haven't tested the program since then until about three minutes ago, which the problem seems to have been resolved. I wouldn't be surprised if the faulty drive had caused the issue, but regardless, thank you for inquiring after it had been awhile.
