### ISSUE TITLE
Wii Games?

### ISSUE THREAD

**Issue by TotallyBecca** [ninstar/Rich-Presence-U#13]
hi! so i had found the switch RPC a few weeks ago, and now that i have my Wii U set up again i had looked for one that can do Wii U games, and this one works wonders, but i noticed that it doesn't support any original Wii games at the moment, and i can't find any rich presence applications for just the Wii.. if it's not too much trouble would you eventually be able to start adding Wii games onto here as well? That would be really really awesome!! I completely understand if you either can't or just don't want to though <3

**Comment by ninstar** [comment]
I personally only maintain the Wii U titles (as the app was originally made with the sole intention of supporting Wii U games), other platforms were made possible thanks to the contribution of other people who keep adding new titles to them, so in that sense Wii is entirely possible if someone is willing to add titles for that console.

Here is the database for all platforms: [https://github.com/ninstar/Rich-Presence-U-DB](https://github.com/ninstar/Rich-Presence-U-DB)

**Comment by Snare-Hawk** [comment]
If you interested in rich presence for Wii games, [RiiTag-RPC](https://github.com/RiiConnect24/RiiTag-RPC) might be what you want. Although, you'll need with a homebrewed Wii to use it.

**Comment by ninstar** [comment]
I'll close this for now, suggestions and pull requests related to games and tiltes can be opened on this repo https://github.com/ninstar/Rich-Presence-U-DB
