### ISSUE TITLE
Game Request: Add FIFA 19 Nintendo Switch Rich Presence

### ISSUE THREAD

**Issue by Moisip** [ninstar/Rich-Presence-U#14]
Hi, I was trying this program and I thought it was great for the games included, but I would like FIFA 19 in Rich Presence U please, thanks.

**Comment by ninstar** [comment]
This repository is for the application code, for games and tiltes we use this one: https://github.com/ninstar/Rich-Presence-U
You can submit your pull request there or (if you have no experience in doing that) use this form: https://forms.gle/dLbBvYcZCSUZU4cY6
