### ISSUE TITLE
you have for wii?

### ISSUE THREAD

**Issue by FranHUB2021** [ninstar/Rich-Presence-U#17]
Hello, I have a question, does this program exist but does it also allow Nintendo Wii?

**Comment by ninstar** [comment]
No. So far no one has volunteered to create and maintain a database of icons and titles for Wii games.

**Comment by ninstar** [comment]
I will be closing this issue for now. If anyone volunteers to add Wii titles, a pull request can be opened in this repository: https://github.com/ninstar/Rich-Presence-U-DB

**Comment by TheAlienDrew** [comment]
@ninstar why not integrate with Rii-Tag and WiiTDB?

**Comment by ninstar** [comment]
> @ninstar why not integrate with Rii-Tag and WiiTDB?

I'm really int how RiiTag works, but there is already an official option for it: https://github.com/RiiConnect24/RiiTag-RPC
About GameTDB, as far as I remember they don't host icons for games, only box and disc arts.

**Comment by TheAlienDrew** [comment]
I assume by "not really into" is because of that little player card sort of thing they use that doesn't interest you?

As for GameTDB, is there a reason why you don't want to use the disc cover logos that they provide? E.g. https://www.gametdb.com/Wii/SAZE52

**Comment by TheAlienDrew** [comment]
> > @ninstar why not integrate with Rii-Tag and WiiTDB?
> 
> I'm not really into how RiiTag works, but there is already an official option for it: https://github.com/RiiConnect24/RiiTag-RPC About GameTDB, as far as I remember they don't host icons for games, only box and disc arts.

Also I am aware of RiiTag-RPC, that's what I'm using at the moment, but while I was trying to fix an issue with Rii-Tag on my Wii U (due to adding the new Aroma homebrew), I stumbled on this, and thought it looked much better for rich presence with the logos, something that Rii-Tag doesn't do.
