### ISSUE TITLE
Doesn't work in latest Godot version

### ISSUE THREAD

**Issue by pifase** [ninstar/Rich-Presence-U#23]
Does not work in Godot version 4.0.1, When pressing the Run Project button (f5) Rich Presence U becomes unresponsive on startup

Edit: Nevermind, I didn't compile the program.

Edit 2: When I exported the program as an .exe file, It did not export correctly

**Comment by ninstar** [comment]
It is not supposed to. As mentioned in the instructions you should use 3.5.1 or later LTS version, 4.0.1 is not a LTS version.
