### ISSUE TITLE
Game Requests

### ISSUE THREAD

**Issue by Aden-Mystio** [ninstar/Rich-Presence-U#24]
Mad Rat Dead
Ghost Trick: Phantom Detective (Switch Remaster)
Polyroll
What Lies In The Multiverse
Toree 3D
Trash Quest
Taiko No Tatsujin: Rhythm Festival
Snake Pass
Brok The InvestiGator
Just Shapes And Beats

**Comment by Aden-Mystio** [comment]
Freedom Planet 2

**Comment by ninstar** [comment]
All requested games in the first commented have been added to the title database, they should be available once you refresh the app. 

> Freedom Planet 2 The NSO Consoles

Freedom Planet 2 is not available on the Nintendo Switch yet, I'll make sure to add it once it is. 
NSO consoles have been present in the database for a long time now.

I also should mention that this repository is for the Rich Presence U application, it is more suitable to use https://github.com/ninstar/Rich-Presence-U-DB for anything related to the title database. If you are not familiar with git you can also request new titles using [this form](https://forms.gle/dLbBvYcZCSUZU4cY6), I always make sure to read all request from time to time.
