### ISSUE TITLE
Exporting for macOS

### ISSUE THREAD

**Issue by ansahtoby12** [ninstar/Rich-Presence-U#30]
What do I put for the 'bundle identifier' when im exporting?
<img width="875" alt="Screenshot 2024-01-02 at 06 58 58" src="https://github.com/ninstar/Rich-Presence-U/assets/124317471/1eb68908-c473-483e-aaca-ca6c91a44ca3">

**Comment by ninstar** [comment]
From the instructions which can be found in the [README.md](https://github.com/ninstar/Rich-Presence-U#compile):

> Add ``com.ninstar.rpc`` to the **identifier** field if you selected **Mac OSX**.

**Comment by ansahtoby12** [comment]
alright thank you
